=== tumillanino/miasma-os/docs/Renoise_3_5_4_Demo_Linux_x86_64/Resources/Schemas/RenoiseDocVersions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="docs">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="renoise"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="renoise">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="RenoiseSong" type="xs:integer" />
        <xs:element name="RenoiseInstrument" type="xs:integer" />
        <xs:element name="RenoiseDeviceChain" type="xs:integer" />
        <xs:element name="FilterDevicePreset" type="xs:integer" minOccurs="0"/>
        <xs:element name="SampleModulationSet" type="xs:integer" minOccurs="0"/>
        <xs:element name="InstrumentPhrase" type="xs:integer" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="version" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tumillanino/miasma-os/docs/Renoise_3_5_4_Demo_Linux_x86_64/Resources/Schemas/RenoiseDocVersions.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

File Extension & XSD definitions
================================

XRNS (Extended Renoise Song) 
  -> RenoiseSongXX.xsd

XRNI (Extended Renoise Instrument) 
  -> RenoiseInstrumentXX.xsd

XRNT (Extended Renoise Track) 
  -> RenoiseDeviceChainsXX.xsd

XRDP (Extended Renoise Device Preset) 
  -> FilterDevicePresetXX.xsd

XRNO (Extended Renoise Modulation Set) 
  -> SampleModulationSetXX.xsd

XRNZ (Extended Renoise Phrase Preset) 
  -> InstrumentPhraseXX.xsd

Note: XRNS, XRNI and old XRNT files are zip containers which can 
be opened with any PKZip compatible tool. The main XML file is 
in the root of the Zip archive. XRNO, XRNZ, XRDP and newer XRNT 
files are plain XML files with a custom file extension.


Renoise Releases & XSD definition versions
==========================================
  
Note: all missing intermediate XSD versions (e.g. RenoiseSong 5-8) can safely 
be ignored. These are only used in "private" alpha/beta releases, which never 
went public.

-->

<docs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RenoiseDocVersions.xsd">  
  <renoise version="180">
     <RenoiseSong>4</RenoiseSong>
     <RenoiseInstrument>2</RenoiseInstrument>
     <RenoiseDeviceChain>3</RenoiseDeviceChain>     
  </renoise>
  <renoise version="190">
     <RenoiseSong>9</RenoiseSong>
     <RenoiseInstrument>5</RenoiseInstrument>
     <RenoiseDeviceChain>5</RenoiseDeviceChain>
     <FilterDevicePreset>1</FilterDevicePreset>
  </renoise>
  <renoise version="191">
     <RenoiseSong>10</RenoiseSong>
     <RenoiseInstrument>6</RenoiseInstrument>
     <RenoiseDeviceChain>6</RenoiseDeviceChain>
     <FilterDevicePreset>1</FilterDevicePreset>
  </renoise>
  <renoise version="200">
     <RenoiseSong>14</RenoiseSong>
     <RenoiseInstrument>7</RenoiseInstrument>
     <RenoiseDeviceChain>7</RenoiseDeviceChain>
     <FilterDevicePreset>2</FilterDevicePreset>
  </renoise>
  <renoise version="210">
     <RenoiseSong>15</RenoiseSong>
     <RenoiseInstrument>7</RenoiseInstrument>
     <RenoiseDeviceChain>8</RenoiseDeviceChain>
     <FilterDevicePreset>3</FilterDevicePreset>
  </renoise>
  <renoise version="250">
     <RenoiseSong>21</RenoiseSong>
     <RenoiseInstrument>7</RenoiseInstrument>
     <RenoiseDeviceChain>10</RenoiseDeviceChain>
     <FilterDevicePreset>4</FilterDevicePreset>
  </renoise>
  <renoise version="260">
     <RenoiseSong>22</RenoiseSong>
     <RenoiseInstrument>8</RenoiseInstrument>
     <RenoiseDeviceChain>11</RenoiseDeviceChain>
     <FilterDevicePreset>5</FilterDevicePreset>
  </renoise>
  <renoise version="270">
     <RenoiseSong>30</RenoiseSong>
     <RenoiseInstrument>12</RenoiseInstrument>
     <RenoiseDeviceChain>12</RenoiseDeviceChain>
     <FilterDevicePreset>6</FilterDevicePreset>
  </renoise>
  <renoise version="280">
     <RenoiseSong>37</RenoiseSong>
     <RenoiseInstrument>13</RenoiseInstrument>
     <RenoiseDeviceChain>16</RenoiseDeviceChain>
     <FilterDevicePreset>9</FilterDevicePreset>
  </renoise>
  <renoise version="300">
     <RenoiseSong>54</RenoiseSong>
     <RenoiseInstrument>24</RenoiseInstrument>
     <RenoiseDeviceChain>18</RenoiseDeviceChain>
     <FilterDevicePreset>10</FilterDevicePreset>
     <SampleModulationSet>1</SampleModulationSet>
     <InstrumentPhrase>0</InstrumentPhrase>
  </renoise>
  <renoise version="310">
     <RenoiseSong>63</RenoiseSong>
     <RenoiseInstrument>31</RenoiseInstrument>
     <RenoiseDeviceChain>19</RenoiseDeviceChain>
     <FilterDevicePreset>11</FilterDevicePreset>
     <SampleModulationSet>4</SampleModulationSet>
     <InstrumentPhrase>2</InstrumentPhrase>
  </renoise>
  <renoise version="320">
     <RenoiseSong>64</RenoiseSong>
     <RenoiseInstrument>32</RenoiseInstrument>
     <RenoiseDeviceChain>20</RenoiseDeviceChain>
     <FilterDevicePreset>12</FilterDevicePreset>
     <SampleModulationSet>5</SampleModulationSet>
     <InstrumentPhrase>2</InstrumentPhrase>
  </renoise>
  <renoise version="330">
     <RenoiseSong>65</RenoiseSong>
     <RenoiseInstrument>33</RenoiseInstrument>
     <RenoiseDeviceChain>21</RenoiseDeviceChain>
     <FilterDevicePreset>13</FilterDevicePreset>
     <SampleModulationSet>5</SampleModulationSet>
     <InstrumentPhrase>2</InstrumentPhrase>
  </renoise>
   <renoise version="350">
     <RenoiseSong>67</RenoiseSong>
     <RenoiseInstrument>34</RenoiseInstrument>
     <RenoiseDeviceChain>22</RenoiseDeviceChain>
     <FilterDevicePreset>11</FilterDevicePreset>
     <SampleModulationSet>5</SampleModulationSet>
     <InstrumentPhrase>3</InstrumentPhrase>
  </renoise>
</docs>
